version: '3.8'

services:
  backend:
    build:
      context: .
    env_file:
      - .env
    ports:
      - ${SPRING_EXTERNAL_PORT}:8080
    container_name: ${SPRING_CONTAINER_NAME}
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
    restart: always
    depends_on:
      - postgres
      - redis
  redis:
    image: redis:alpine
    container_name: cache
    ports:
      - ${HOST_PORT_REDIS}:${CONTAINER_PORT_REDIS}
    volumes:
      - ./redis-data:/data
  postgres:
    image: postgres:18-alpine3.22
    restart: always
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}
    logging:
      options:
        max-size: 10m
        max-file: '10' # good
    volumes:
      # chmod +x ./postgres-initdb.sh
      # chmod +x ./sql
      # any problem exec : docker-compose down --volumes; docker volume prune
      #- postgres-data2:/var/lib/postgresql/_data
      - postgresql_data:/var/lib/postgresql/data
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      #- ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
      #- ${POSTGRES_DATA}:/var/lib/postgresql/data
    healthcheck:
      #CHANGE 1: this command checks if the database is ready, right on the source db server
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgresql_data:
    driver: local

networks:
  postgres_network:
    driver: bridge
